"""PROTOCOL Part II, step 0a: re-score all logged agent trials and the baselines.

    python scripts/rescore_v2.py              # -> experiments/reports/V2_0a_rescore.md (+ CSVs in v2_0a/)
    python scripts/rescore_v2.py --workers 12

Nothing is retrained and no trial is logged. Every agent is measured through its
STORED exposures and its SAVED weights with harness/diagnostics.agent_scores, on
its primary evaluation set at 10 bp: LC1 (learning curve), LC2 (0 vs 10 bp), LC3
(timing IC / Sharpe), LC4 (attribution vs buy-and-hold), LC5/LC7 (action gap,
predicted vs realised value, reproduction check), LC6 (switches, time at full
exposure), LC8 (lag-1 execution, gate G-lag) and the H3 drawdown preview.
Baselines get the exposure-based part (harness/diagnostics.strategy_scores); the
descriptive vol-target baseline is run once and logged as a baseline row, not a trial.
"""

import argparse
import os
import shutil
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import pandas as pd                                                         # noqa: E402

from harness import diagnostics as dg                                       # noqa: E402
from harness import trials as tr                                            # noqa: E402
from harness.config import load_config, repo_path                           # noqa: E402
from harness.data import load_prices, ticker_sets                           # noqa: E402
from harness.experiment import BaselinePolicy, load_result, run_experiment  # noqa: E402
from harness.report import fmt, latest_dir                                  # noqa: E402
from rl.features import ex_ante_vol                                         # noqa: E402

BASELINES = ["baseline_buy_and_hold", "baseline_momentum", "baseline_macd", "baseline_random",
             "baseline_momentum_252", "baseline_vol_target"]
OUT = repo_path("experiments", "reports", "v2_0a")
G_LAG_TOL = dg.G_LAG_TOL


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--workers", type=int, default=12)
    ap.add_argument("--threads", type=int, default=2)
    ap.add_argument("--skip-q", action="store_true", help="skip the Q-value inference (LC5/LC7)")
    args = ap.parse_args()
    os.makedirs(OUT, exist_ok=True)

    cfg0 = load_config()
    primary = cfg0["evaluation"]["costs"]["primary_bps"]
    allp = load_prices(ticker_sets(cfg0)["all"], cfg0)
    sigmas = {t: ex_ante_vol(df["Close"].to_numpy(), 60) for t, df in allp.items()}
    bh = load_result(latest_dir("baseline_buy_and_hold"))

    # the descriptive baseline: run once, logged as a BASELINE row (never a trial)
    if latest_dir("baseline_vol_target") is None:
        print("[0a] running the descriptive vol-target baseline (logged as a baseline row)")
        run_experiment(load_config("config/experiments/baseline_vol_target.yaml"),
                       notes="descriptive baseline (PROTOCOL Part II step 0a)", verbose=False)

    # agents: the latest trial of every agent configuration
    trials = tr.load_trials()
    rows, qrows, lcrows = [], [], []
    for _, t in trials[trials["kind"] == "agent"].drop_duplicates("name", keep="last").iterrows():
        print(f"[0a] {t['name']}")
        row, d, lc, q = dg.agent_scores(t["name"], load_result(repo_path(t["output_dir"])), bh, sigmas, primary,
                                        workers=args.workers, threads=args.threads, q_values=not args.skip_q)
        d.assign(strategy=t["name"]).to_csv(os.path.join(OUT, f"diag_{t['name']}.csv"), index=False)
        rows.append(row)
        lcrows.append(lc.assign(strategy=t["name"]))
        if q is not None:
            qrows.append(q.assign(strategy=t["name"]))
    agents_df = pd.DataFrame(rows)
    agents_df.to_csv(os.path.join(OUT, "agents.csv"), index=False)
    if qrows:
        pd.concat(qrows).to_csv(os.path.join(OUT, "q_diagnostics_per_sleeve.csv"), index=False)
    pd.concat(lcrows).to_csv(os.path.join(OUT, "learning_curves_per_job.csv"), index=False)

    # baselines on the two main sets
    brows = []
    for name in BASELINES:
        d = latest_dir(name)
        if d is None:
            print(f"[0a] skip {name}: not logged")
            continue
        res = load_result(d)
        for es in ("single", "train"):
            print(f"[0a] {name} ({es})")
            pol = BaselinePolicy(res.cfg["policy"], res.cfg.get("policy_params"))
            brows.append(dg.strategy_scores(name.replace("baseline_", ""), res, pol, es, bh, sigmas, primary)[0])
    base_df = pd.DataFrame(brows)
    base_df.to_csv(os.path.join(OUT, "baselines.csv"), index=False)
    shutil.rmtree(repo_path("experiments", "runs", "_unlogged"), ignore_errors=True)
    write_report(agents_df, base_df, primary)


def write_report(agents_df, base_df, primary):
    L = ["# v2 step 0a — Re-scoring of all logged trials (generated by scripts/rescore_v2.py)", "",
         "No retraining and no new trials: agents are measured through their stored exposures and saved "
         "weights. Medians over 10 seeds × 5 folds on each trial's primary evaluation set (^GDAXI = `single`, "
         f"26 ETFs = `train`), net of {primary} bp + 1 bp unless stated. Definitions: PROTOCOL Part II §V7 and "
         "`harness/diagnostics.py`. Per-row CSVs: `experiments/reports/v2_0a/`.", "",
         "## 1. Performance, attribution and execution lag", "",
         "LC4: *timing* = median gross (0 bp) Sharpe − median B&H Sharpe; *cost* = median net − median gross, so "
         "net − B&H = timing + cost. LC8: *Δ lag* = median lag-1 net Sharpe − median lag-0 net Sharpe; gate G-lag "
         f"(§V8) passes if Δ lag ≥ −{G_LAG_TOL}. It is binding only for the configuration selected for M5. "
         "Baselines are deterministic, so their medians are over 5 folds only and Δ lag is noisy "
         "(a one-day delay moves each 2-year fold's Sharpe by ~0.1 for a strategy that switches 13×/yr). "
         "Paired medians are in the CSVs (`*_paired`).", "",
         "| Strategy | Set | Sharpe 10 bp | 0 bp | B&H | Timing vs B&H (Sharpe / %·yr) | Cost (Sharpe / %·yr) | Lag-1 Sharpe | Δ lag | G-lag |",
         "|---|---|---|---|---|---|---|---|---|---|"]
    for df, mark in ((agents_df, ""), (base_df, "*")):
        for _, r in df.iterrows():
            nm = f"{mark}{r['strategy']}{mark}"
            L.append(f"| {nm} | {r['eval_set']} | {fmt(r['sharpe_10bp'])} | {fmt(r['sharpe_0bp'])} | {fmt(r['bh_sharpe'])} | "
                     f"{fmt(r['timing_vs_bh_sharpe'])} / {fmt(r['timing_vs_bh_pct'], 1)} | {fmt(r['cost_sharpe'])} / {fmt(r['cost_pct'], 1)} | "
                     f"{fmt(r['sharpe_10bp_lag1'])} | {fmt(r['lag_delta'])} | {'pass' if r['g_lag_pass'] else 'FAIL'} |")
    L += ["", "## 2. Timing skill and behaviour", "",
          "| Strategy | Set | Timing IC | Timing Sharpe | Mean exposure | Switches / 100 bars | Time at 100 % |",
          "|---|---|---|---|---|---|---|"]
    for df, mark in ((agents_df, ""), (base_df, "*")):
        for _, r in df.iterrows():
            L.append(f"| {mark}{r['strategy']}{mark} | {r['eval_set']} | {fmt(r['timing_ic'], 3)} | {fmt(r['timing_sharpe'])} | "
                     f"{fmt(r['mean_exposure'], pct=True)} | {fmt(r['switches_per_100'], 1)} | {fmt(r['time_at_anchor'], pct=True)} |")
    if "action_gap_ratio" in agents_df:
        L += ["", "## 3. Learning curves and value estimates (agents)", "",
              "LC1 from `curve.csv` (inner-validation Sharpe; AUC = mean over training; slope per unit of training "
              "progress over the second half). LC5/LC7 from re-running the selected checkpoint; G truncated at the "
              "block end, bars with < 300 bars left excluded. *Action-gap ratio* < 1 = the greedy choice is decided "
              "by noise. *Over-estimation* = (mean Q − mean G) / SD(G), scale-free so it compares across rewards "
              "(Q − G in reward units and Q / G are in the CSVs). *Reproduced* = share of decision bars whose "
              "re-computed exposure equals the stored one.", "",
              "| Strategy | LC1 AUC | Last-half slope | Best ckpt at | Action-gap ratio | Over-estimation (SD of G) | corr(Q, G) | Reproduced |",
              "|---|---|---|---|---|---|---|---|"]
        for _, r in agents_df.iterrows():
            L.append(f"| {r['strategy']} | {fmt(r['lc_auc'])} | {fmt(r['lc_last_half_slope'])} | {fmt(r['lc_best_at'], pct=True)} | "
                     f"{fmt(r['action_gap_ratio'], 3)} | {fmt(r['q_bias_sd'])} | {fmt(r['q_G_corr'])} | "
                     f"{fmt(r['reproduced'], pct=True)} |")
    L += ["", "## 4. H3 preview (descriptive): drawdown beyond lower exposure", "",
          "Exposure-matched buy-and-hold = each sleeve earns (agent's mean exposure) × asset return, daily "
          "rebalanced, no costs. Vol-matched = the same with the agent's realised volatility instead of its mean "
          "exposure. Negative ΔMDD = smaller drawdown than the benchmark. Descriptive only; the H3 test itself is "
          "pre-registered for the v2 configurations (§V4).", "",
          "| Strategy | Set | Share of (seed, fold) with MDD lower by > 0.1 pp | median ΔMDD vs matched | vs vol-matched |",
          "|---|---|---|---|---|"]
    for df, mark in ((agents_df, ""), (base_df, "*")):
        for _, r in df.iterrows():
            L.append(f"| {mark}{r['strategy']}{mark} | {r['eval_set']} | {fmt(r['h3_share_mdd_below_matched'], pct=True)} | "
                     f"{fmt(100 * r['h3_dmdd_matched'], 1)} pp | {fmt(100 * r['h3_dmdd_volmatched'], 1)} pp |")
    out = repo_path("experiments", "reports", "V2_0a_rescore.md")
    with open(out, "w") as fh:
        fh.write("\n".join(L) + "\n")
    print("report ->", out)


if __name__ == "__main__":
    main()
