"""Re-score finished trials under the named cost scenarios (config/cost_scenarios.yaml).

    python scripts/rescore_costs.py        # -> experiments/reports/cost_scenarios.md

No retraining and NOTHING is appended to experiments/trials.csv. The
exposures are exactly those the trial produced (agents: the saved, selected
checkpoints; baselines: recomputed deterministically), so a re-score
measures the same strategies under other costs. It is not a new trial.

Three sections:
  1. single asset ^GDAXI: every agent trial and baseline, PROTOCOL 10 bp vs
     the neo-broker scenario and its sensitivity variants
  2. 26-ETF portfolio (baselines only): how a flat per-transaction fee scales
     when EUR 10,000 is split over 26 positions
  3. statistics under neo_broker (single asset): paired permutation tests vs
     the four baselines (Holm) and the deflated Sharpe ratio (N_trials from
     the trial log)
"""

import os
import shutil
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


from harness import trials as tr                                    # noqa: E402
from harness.backtest import load_scenarios                         # noqa: E402
from harness.config import repo_path                                # noqa: E402
from harness.report import latest_dir                               # noqa: E402
from harness.experiment import (BaselinePolicy, compare_to_baselines,      # noqa: E402
                                deflated_sharpe_of, load_result, run_experiment)

AGENTS = ["legacy", "m2_dqn_base", "m2_dqn_dueling", "m2_dqn_nstep", "m2_dqn_per",
          "m3_dqn_base_100k", "nb_dqn_base", "nb_dqn_k2"]
TRAINED_NEO = {"nb_dqn_base", "nb_dqn_k2"}     # trained under neo-broker costs (marked †)
BASES = ["baseline_buy_and_hold", "baseline_momentum", "baseline_macd", "baseline_random"]


def rescore(name, eval_sets):
    d = latest_dir(name)
    if d is None:
        print(f"  skip {name}: not logged yet")
        return None
    cfg = load_result(d).cfg
    if cfg.get("kind") == "agent":
        from rl.policy import StoredExposurePolicy
        policy = StoredExposurePolicy(repo_path(d))
    else:
        policy = BaselinePolicy(cfg["policy"], cfg.get("policy_params"))
    primary = cfg["evaluation"]["costs"]["primary_bps"]
    return run_experiment(cfg, policy=policy, eval_sets=eval_sets, cost_levels=[primary],
                          cost_scenarios=list(load_scenarios()), log=False, verbose=False)


def row(name, res, es, cols):
    """Median Sharpe per cost setting + neo-broker trading activity."""
    cells = [f"{res.runs(es, c)['sharpe'].median():.2f}" for c in cols]
    nb = res.runs(es, "neo_broker")
    return (f"| {name} | " + " | ".join(cells) +
            f" | {nb['trades_per_year'].median():.1f} | {nb['turnover'].median():.1f} |")


def main():
    scen = list(load_scenarios())
    cols = [10] + scen
    head = ("| Strategy | 10 bp (H1) | " + " | ".join(scen) +
            " | Transactions / yr | Turnover / yr |")
    sep = "|---" * (len(cols) + 3) + "|"

    L = ["# Cost scenarios: re-scored trials (generated by scripts/rescore_costs.py)", "",
         "Median annualised net Sharpe over 10 seeds x 5 walk-forward folds (validation 2014-01 → 2023-09). "
         "Same exposures as the logged trials; only the cost model differs, so these are **not** new trials.",
         "Scenarios (config/cost_scenarios.yaml): `neo_broker` = EUR 1 for every transaction (each buy and each "
         "sell) on EUR 10,000, 3 bp half-spread, 15 bp/yr TER on held ^GDAXI exposure (ETF prices are already "
         "net of TER). Variants change capital (1k / 50k) or half-spread (1 / 5 bp).", "",
         "## 1. Single asset ^GDAXI (agents and baselines)", "",
         "† = trained under neo-broker costs; all other agents trained at 10 bp + 1 bp.", "", head, sep]
    single = {}
    for name in AGENTS + BASES:
        res = rescore(name, ["single"])
        if res is None:
            continue
        single[name] = res
        label = (f"*{name.replace('baseline_', '')}*" if name.startswith("baseline_")
                 else name + (" †" if name in TRAINED_NEO else ""))
        L.append(row(label, res, "single", cols))

    L += ["", "## 2. 26-ETF training-universe portfolio (baselines)", "",
          "With EUR 10,000 split over 26 positions each sleeve holds ≈ EUR 385, so one EUR 1 "
          "transaction costs ≈ 26 bp of that sleeve; on a ¼-exposure step it is ≈ 104 bp of the traded amount.", "",
          head, sep]
    for name in BASES:
        res = rescore(name, ["train"])
        if res is not None:
            L.append(row("*" + name.replace("baseline_", "") + "*", res, "train", cols))

    bases = {b.replace("baseline_", ""): single[b] for b in BASES if b in single}
    L += ["", "## 3. Statistics under `neo_broker` (single asset ^GDAXI)", "",
          f"N_trials (agent configurations in the trial log) = {tr.n_trials()}. "
          "Cells: mean difference in annualised Sharpe (agent − baseline) over 50 (seed, fold) pairs, "
          "one-sided Holm-adjusted p.", "",
          "| Agent | vs buy&hold | vs momentum | vs MACD | vs random | Deflated Sharpe (median over seeds) |",
          "|---|---|---|---|---|---|"]
    for name in AGENTS:
        if name not in single:
            continue
        comp = compare_to_baselines(single[name], bases, eval_set="single", cost_bps="neo_broker").set_index("baseline")
        dsr = deflated_sharpe_of(single[name], eval_set="single", cost_bps="neo_broker")
        cells = [f"{comp.loc[b, 'mean_diff']:+.2f}, p={comp.loc[b, 'p_holm']:.3f}" for b in bases]
        label = name + (" †" if name in TRAINED_NEO else "")
        L.append(f"| {label} | " + " | ".join(cells) + f" | {dsr['deflated_sharpe_median']:.3f} |")

    out = repo_path("experiments", "reports", "cost_scenarios.md")
    with open(out, "w") as fh:
        fh.write("\n".join(L) + "\n")
    shutil.rmtree(repo_path("experiments", "runs", "_unlogged"), ignore_errors=True)
    print("\n".join(L))
    print("report ->", out)


if __name__ == "__main__":
    main()
