"""Milestone M1: evaluate all baselines with the harness and check reproducibility.

    python scripts/run_baselines.py                  # 4 baselines, logged to experiments/trials.csv
    python scripts/run_baselines.py --no-log         # dry run, nothing written
    python scripts/run_baselines.py --descriptive    # also momentum lookbacks 20/120/252 (descriptive only)

What it does
  1. runs each baseline config over 5 folds x 10 seeds x {train, leave_out, single} x cost sweep
  2. runs each one a SECOND time without logging and checks that every metric
     is bit-identical (the M1 go criterion: "baseline metrics are reproducible")
  3. writes a markdown report to experiments/reports/M1_baselines.md
"""

import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import numpy as np                                                    # noqa: E402
import pandas as pd                                                   # noqa: E402

from harness.config import load_config, repo_path                     # noqa: E402
from harness.experiment import run_experiment                         # noqa: E402

BASELINE_CONFIGS = ["buy_and_hold", "momentum", "macd", "random"]
COLUMNS = [("sharpe", "Sharpe"), ("cagr", "CAGR"), ("max_drawdown", "MaxDD"),
           ("turnover", "Turnover/yr"), ("exposure", "Exposure"), ("avg_holding", "Hold (bars)"),
           ("hit_rate", "Hit rate")]


def fmt(med, iqr, pct=False):
    if not np.isfinite(med):
        return "n/a"
    if pct:
        return f"{100 * med:.1f}% ({100 * iqr:.1f})"
    return f"{med:.2f} ({iqr:.2f})"


def table(results, eval_set, cost):
    """Markdown table: median (IQR) over seeds x folds, one row per baseline."""
    head = "| Baseline | " + " | ".join(c[1] for c in COLUMNS) + " |"
    sep = "|---" * (len(COLUMNS) + 1) + "|"
    lines = [head, sep]
    for name, res in results.items():
        s = res.summary[f"{eval_set}@{cost}bp"]
        cells = [fmt(s[f"{k}_median"], s[f"{k}_iqr"], pct=k in ("cagr", "max_drawdown", "hit_rate", "exposure"))
                 for k, _ in COLUMNS]
        lines.append(f"| {name} | " + " | ".join(cells) + " |")
    return "\n".join(lines)


def fold_table(results, eval_set, cost):
    """Median Sharpe per fold: shows how much the market regime matters."""
    folds = list(next(iter(results.values())).summary[f"{eval_set}@{cost}bp"]["fold_sharpe_median"])
    lines = ["| Baseline | " + " | ".join(folds) + " |", "|---" * (len(folds) + 1) + "|"]
    for name, res in results.items():
        f = res.summary[f"{eval_set}@{cost}bp"]["fold_sharpe_median"]
        lines.append(f"| {name} | " + " | ".join(f"{f[k]:.2f}" for k in folds) + " |")
    return "\n".join(lines)


def main():
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--no-log", action="store_true", help="do not write trials.csv / outputs")
    p.add_argument("--descriptive", action="store_true", help="add momentum lookbacks 20/120/252")
    args = p.parse_args()

    base_cfg = load_config()
    primary = base_cfg["evaluation"]["costs"]["primary_bps"]
    sweep = base_cfg["evaluation"]["costs"]["sweep_bps"]

    jobs = [(name, load_config(f"config/experiments/baseline_{name}.yaml"), "") for name in BASELINE_CONFIGS]
    if args.descriptive:
        for lb in base_cfg["evaluation"]["baselines"]["momentum_descriptive"]:
            cfg = load_config("config/experiments/baseline_momentum.yaml",
                              {"name": f"baseline_momentum_{lb}", "policy_params": {"lookback": lb}})
            jobs.append((f"momentum_{lb}", cfg, "descriptive only (PROTOCOL §6)"))

    results, reproducible = {}, {}
    for name, cfg, note in jobs:
        print(f"== {name}")
        res = run_experiment(cfg, log=not args.no_log, notes=note, verbose=False)
        again = run_experiment(cfg, log=False, verbose=False)        # reproducibility check
        try:
            pd.testing.assert_frame_equal(res.metrics, again.metrics, check_exact=True)
            reproducible[name] = True
        except AssertionError:
            reproducible[name] = False
        results[name] = res
        s = res.summary[f"train@{primary}bp"]
        print(f"   train@{primary}bp Sharpe median {s['sharpe_median']:.3f} (IQR {s['sharpe_iqr']:.3f})"
              f" | reproducible: {reproducible[name]} | {res.trial_id or '(not logged)'}")

    lines = ["# M1 — Baseline results (generated by scripts/run_baselines.py)", "",
             "Cells: median (IQR) over 10 seeds x 5 walk-forward folds (F1-F5, 2014-01 → 2023-09).",
             "Each (seed, fold) value is the metric of an equal-weight portfolio over the evaluation set.",
             "CAGR, MaxDD, exposure and hit rate in %. Turnover in multiples of capital per year.",
             f"Costs: c + {base_cfg['evaluation']['costs']['half_spread_bps']} bp half-spread per unit traded.", ""]
    for es in ["train", "leave_out", "single"]:
        for c in [primary] + [x for x in sweep if x != primary]:
            lines += [f"## {es} @ c = {c} bp", "", table(results, es, c), ""]
        lines += [f"### {es}: median Sharpe per fold @ {primary} bp", "", fold_table(results, es, primary), ""]
    lines += ["## Reproducibility (M1 go criterion)", "",
              "| Baseline | identical metrics on re-run |", "|---|---|"]
    lines += [f"| {k} | {'yes' if v else '**NO**'} |" for k, v in reproducible.items()]

    if not args.no_log:
        out = repo_path("experiments", "reports", "M1_baselines.md")
        os.makedirs(os.path.dirname(out), exist_ok=True)
        with open(out, "w") as fh:
            fh.write("\n".join(lines) + "\n")
        print("report ->", out)
    else:
        print("\n".join(lines))
    if not all(reproducible.values()):
        sys.exit("M1 FAILED: some baseline metrics were not reproducible")


if __name__ == "__main__":
    main()
